### ISSUE TITLE
Kerberize cluster

### ISSUE THREAD

**Issue by chandrap08** [chandrap08/SEBC#9]

**Comment by chandrap08** [comment]
Enabling kerberos encryption type has an error:

/usr/share/cmf/bin/import_credentials.sh failed with exit code 1 and output of <<
+ export PATH=/usr/kerberos/bin:/usr/kerberos/sbin:/usr/lib/mit/sbin:/usr/sbin:/usr/lib/mit/bin:/usr/bin:/sbin:/usr/sbin:/bin:/usr/bin
+ PATH=/usr/kerberos/bin:/usr/kerberos/sbin:/usr/lib/mit/sbin:/usr/sbin:/usr/lib/mit/bin:/usr/bin:/sbin:/usr/sbin:/bin:/usr/bin
+ KEYTAB_OUT=/var/run/cloudera-scm-server/cmf1551168524395091650.keytab
+ USER=cloudera-scm/admin@CHANDRAP08.CO.UK
+ PASSWD=REDACTED
+ KVNO=1
+ SLEEP=0
+ RHEL_FILE=/etc/redhat-release
+ '[' -f /etc/redhat-release ']'
+ set +e
+ grep Tikanga /etc/redhat-release
+ '[' 1 -eq 0 ']'
+ '[' 0 -eq 0 ']'
+ grep 'CentOS release 5' /etc/redhat-release
+ '[' 1 -eq 0 ']'
+ '[' 0 -eq 0 ']'
+ grep 'Scientific Linux release 5' /etc/redhat-release
+ '[' 1 -eq 0 ']'
+ set -e
+ '[' -z /var/run/cloudera-scm-server/krb5558171798824020841.conf ']'
+ echo 'Using custom config path '\''/var/run/cloudera-scm-server/krb5558171798824020841.conf'\'', contents below:'
+ cat /var/run/cloudera-scm-server/krb5558171798824020841.conf
+ IFS=' '
+ read -a ENC_ARR
+ for ENC in '"${ENC_ARR[@]}"'
+ echo 'addent -password -p cloudera-scm/admin@CHANDRAP08.CO.UK -k 1 -e rc4-hmac'
+ ktutil
+ '[' 0 -eq 1 ']'
+ echo REDACTED
+ echo 'wkt /var/run/cloudera-scm-server/cmf1551168524395091650.keytab'
+ chmod 600 /var/run/cloudera-scm-server/cmf1551168524395091650.keytab
+ kinit -k -t /var/run/cloudera-scm-server/cmf1551168524395091650.keytab cloudera-scm/admin@CHANDRAP08.CO.UK
kinit: KDC has no support for encryption type while getting initial credentials


# krb5.conf
[libdefaults]
default_realm = CHANDRAP08.CO.UK
allow_weak_crypto = true
dns_lookup_kdc = false
dns_lookup_realm = false
ticket_lifetime = 604800
renew_lifetime = 604800
forwardable = true
default_tgs_enctypes = rc4-hmac
default_tkt_enctypes = rc4-hmac
permitted_enctypes = rc4-hmac
udp_preference_limit = 1
kdc_timeout = 3000
[realms]
CHANDRAP08.CO.UK = {
kdc = ip-172-31-16-183.eu-west-1.compute.internal
admin_server = ip-172-31-16-183.eu-west-1.compute.internal
}

[domain_realm]
eu-west-1.compute.internal = CHANDRAP08.CO.UK
.eu-west-1.compute.internal = CHANDRAP08.CO.UK

#kdc.conf file
[kdcdefaults]
 kdc_ports = 88
 kdc_tcp_ports = 88

[realms]
 CHANDRAP08.CO.UK = {
  #master_key_type = aes256-cts
  acl_file = /var/kerberos/krb5kdc/kadm5.acl
  dict_file = /usr/share/dict/words
  admin_keytab = /var/kerberos/krb5kdc/kadm5.keytab
  supported_enctypes = aes256-cts:normal aes128-cts:normal des3-hmac-sha1:normal arcfour-hmac:normal camellia256-cts:normal camellia128-cts:normal des-hmac-sha1:normal des-cbc-md5:normal des-cbc-crc:normal
  max_life = 1d
  max_renewable_life = 7d
 }

**Comment by chandrap08** [comment]
Keytab file creation seemed fine:

[ec2-user@ip-172-31-16-183 ~]$ sudo kadmin.local
Authenticating as principal root/admin@CHANDRAP08.CO.UK with password.
kadmin.local:  xst -k theresa.keytab theresa/user@CHANDRAP08.CO.UK
Entry for principal theresa/user@CHANDRAP08.CO.UK with kvno 3, encryption type aes256-cts-hmac-sha1-96 added to keytab WRFILE:theresa.keytab.
Entry for principal theresa/user@CHANDRAP08.CO.UK with kvno 3, encryption type aes128-cts-hmac-sha1-96 added to keytab WRFILE:theresa.keytab.
Entry for principal theresa/user@CHANDRAP08.CO.UK with kvno 3, encryption type des3-cbc-sha1 added to keytab WRFILE:theresa.keytab.
Entry for principal theresa/user@CHANDRAP08.CO.UK with kvno 3, encryption type arcfour-hmac added to keytab WRFILE:theresa.keytab.
Entry for principal theresa/user@CHANDRAP08.CO.UK with kvno 3, encryption type camellia256-cts-cmac added to keytab WRFILE:theresa.keytab.
Entry for principal theresa/user@CHANDRAP08.CO.UK with kvno 3, encryption type camellia128-cts-cmac added to keytab WRFILE:theresa.keytab.
Entry for principal theresa/user@CHANDRAP08.CO.UK with kvno 3, encryption type des-hmac-sha1 added to keytab WRFILE:theresa.keytab.
Entry for principal theresa/user@CHANDRAP08.CO.UK with kvno 3, encryption type des-cbc-md5 added to keytab WRFILE:theresa.keytab.

The KDS server failed to start.

[ec2-user@ip-172-31-16-183 ~]$ systemctl status kadmin.service
● kadmin.service - Kerberos 5 Password-changing and Administration
   Loaded: loaded (/usr/lib/systemd/system/kadmin.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-06-09 07:27:29 EDT; 19s ago
  Process: 15902 ExecStart=/usr/sbin/_kadmind -P /var/run/kadmind.pid $KADMIND_ARGS (code=exited, status=1/FAILURE)

Jun 09 07:27:29 ip-172-31-16-183.eu-west-1.compute.internal kadmind[15902]: setsockopt(10,IPV6_V6ONLY,1) worked
Jun 09 07:27:29 ip-172-31-16-183.eu-west-1.compute.internal kadmind[15902]: listening on fd 10: udp ::.464 (pktinfo)
Jun 09 07:27:29 ip-172-31-16-183.eu-west-1.compute.internal kadmind[15902]: setsockopt(11,IPV6_V6ONLY,1) worked
Jun 09 07:27:29 ip-172-31-16-183.eu-west-1.compute.internal kadmind[15902]: listening on fd 12: tcp 0.0.0.0.464
Jun 09 07:27:29 ip-172-31-16-183.eu-west-1.compute.internal _kadmind[15902]: kadmind: kadmind: Cannot set GSSAPI authentication names, aborting
Jun 09 07:27:29 ip-172-31-16-183.eu-west-1.compute.internal kadmind[15902]: listening on fd 11: tcp ::.464
Jun 09 07:27:29 ip-172-31-16-183.eu-west-1.compute.internal systemd[1]: kadmin.service: control process exited, code=exited status=1
Jun 09 07:27:29 ip-172-31-16-183.eu-west-1.compute.internal systemd[1]: Failed to start Kerberos 5 Password-changing and Administration.
Jun 09 07:27:29 ip-172-31-16-183.eu-west-1.compute.internal systemd[1]: Unit kadmin.service entered failed state.
Jun 09 07:27:29 ip-172-31-16-183.eu-west-1.compute.internal systemd[1]: kadmin.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by mfernest** [comment]
Running this from the command line with KRB5_TRACE=/dev/console might have revealed more. It's not obvious to me from the stuff above what went wrong.
